// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class GameManager
{

	static GameManager _instance;

	public static GameManager Instance
	{
		get {
			if (_instance == null) 
				_instance = new GameManager();
			return _instance;
		}
	}

	public bool Running { get; set; }

	public enum MechTypes
	{
		Old,
		New
	}

	public MechTypes MechType { get; set; }

}

