// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class GameManager
{
	public enum GameModes {
		Overview,
		ThirdPerson
	}

	public GameModes CurrentMode = GameModes.Overview;

	public delegate void ChangeModeEventHandler (GameModes newMode, GameModes oldMode);
	public event ChangeModeEventHandler ModeChanged;

	static GameManager _instance;

	public static GameManager Instance
	{
		get {
			if (_instance == null) 
				_instance = new GameManager();
			return _instance;
		}
	
	}

	public bool Running
	{
		get {
			return _instance.CurrentMode == GameModes.ThirdPerson;
		}
	}


	public bool Paused
	{
		get {
			return _instance.CurrentMode == GameModes.Overview;
		}
	}


	public void SwitchToThirdPersonMode()
	{
		var oldMode = CurrentMode;
		CurrentMode = GameModes.ThirdPerson;
		if (ModeChanged != null)
			ModeChanged.Invoke(CurrentMode, oldMode);
	}

	public void SwitchToOverviewMode()
	{
		var oldMode = CurrentMode;
		CurrentMode = GameModes.Overview;
		if (ModeChanged != null)
			ModeChanged.Invoke(CurrentMode, oldMode);
	}
}

